import pygame
import time

SCREEN_WIDTH = 2560 / 1.75
SCREEN_HEIGHT = 1440 / 1.75
SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
CLOCK = pygame.time.Clock()

class Order:
    def __init__(self):
        self.TURN = 'Player 1'
        self.PHASE = 'Untap'
        self.PRIORITY = 'Player 1'
        self.STACK = []

ORDER = Order()
    
PLAYER_DECK_X = 30
PLAYER_DECK_Y = 530
PLAYER_DECK_WIDTH = 672 / 7
PLAYER_DECK_HEIGHT = 936 / 7

PLAYER_GRAVE_X = PLAYER_DECK_X + PLAYER_DECK_WIDTH + 10
PLAYER_GRAVE_Y = PLAYER_DECK_Y
PLAYER_GRAVE_WIDTH = PLAYER_DECK_WIDTH
PLAYER_GRAVE_HEIGHT = PLAYER_DECK_HEIGHT

OPPONENT_DECK_X = SCREEN_WIDTH - 210
OPPONENT_DECK_Y = 100
OPPONENT_DECK_WIDTH = 672 / 7
OPPONENT_DECK_HEIGHT = 936 / 7

OPPONENT_GRAVE_X = OPPONENT_DECK_X - OPPONENT_DECK_WIDTH - 10
OPPONENT_GRAVE_Y = OPPONENT_DECK_Y
OPPONENT_GRAVE_WIDTH = OPPONENT_DECK_WIDTH
OPPONENT_GRAVE_HEIGHT = OPPONENT_DECK_HEIGHT

PLAYER_CARD_WIDTH = 672 / 6
PLAYER_CARD_HEIGHT = 936 / 6

PLAYER_HAND_HEIGHT = PLAYER_CARD_HEIGHT
PLAYER_HAND_WIDTH = SCREEN_WIDTH - 800
PLAYER_HAND_X = 400
PLAYER_HAND_Y = SCREEN_HEIGHT - PLAYER_CARD_HEIGHT - 20

OPPONENT_CARD_WIDTH = 672 / 7
OPPONENT_CARD_HEIGHT = 936 / 7

OPPONENT_HAND_HEIGHT = OPPONENT_CARD_HEIGHT
OPPONENT_HAND_WIDTH = PLAYER_HAND_WIDTH * 6 / 7 
OPPONENT_HAND_X = PLAYER_HAND_X * 7 / 6
OPPONENT_HAND_Y = 0 - OPPONENT_CARD_HEIGHT / 3

PLAYER_BATTLEFIELD_X = 250
PLAYER_BATTLEFIELD_Y = SCREEN_HEIGHT / 2 

OPPONENT_BATTLEFIELD_X = 110
OPPONENT_BATTLEFIELD_Y = 110

PERMANENT_WIDTH = 672 / 7
PERMANENT_HEIGHT = 936 / 7
BATTLEFIELD_SPACE = 10
BATTLEFIELD_WIDTH = SCREEN_WIDTH - PLAYER_BATTLEFIELD_X - 50

PLAYER_LIFE_X = 50
PLAYER_LIFE_Y = 700
OPPONENT_LIFE_X = SCREEN_WIDTH - 180
OPPONENT_LIFE_Y = 30

PLAYER_MANA_POOL_X = 200
PLAYER_MANA_POOL_Y = 700
OPPONENT_MANA_POOL_X = SCREEN_WIDTH - 250
OPPONENT_MANA_POOL_Y = 30

PHASE_X = 20
PHASE_Y = 20

STACK_X = 100
STACK_Y = (SCREEN_HEIGHT - PLAYER_CARD_HEIGHT) / 2